spring:
  profiles:
    active: dev #默认环境

---
server:
  port: 8888
  max-http-header-size: 4048576 #Request header is too large异常解决
spring:
  application:
    name: COMMON-SERVICE
	data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 127.0.0.1:9300
  profiles: dev #dev环境
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka

---
server:
  port: 8889
  max-http-header-size: 4048576 #Request header is too large异常解决
spring:
  application:
    name: COMMON-SERVICE
	data:
		elasticsearch:
			cluster-name: elasticsearch
			cluster-nodes: 127.0.0.1:9300	
  profiles: test #test环境
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
