spring:
  profiles:
    active: dev #默认环境

---    
server:
  port: 9527
spring:
  application:
    name: MICROSERVICE-ZUUL-GATEWAY  #路由名称
  profiles: dev #环境
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka #注册中心地址
  instance:
    instance-id: gateway-9527 #注册中心显示的名字
    prefer-ip-address: true  #注册中心左下角显示ip（可以不要）
zuul:
  routes:
    plat.serviceId: plat-service #做映射，服务提供者的服务名（plat随便取）
    plat.path: /plat/**   #访问的时候，是/plat打头的地址，就使用plat-service来响应做映射：解决地址太长了，服务名的暴露的问题
		product.serviceId: product-service 
		product.path: /product/**   
  ignored-services: "*"  #禁止使用服务名访问:如果有很多，可以直接使用"*"忽略所有
  prefix: "/aigou"  # 统一前缀（访问的路径加上前缀）
